### ISSUE TITLE
"FIXME: what?" in fnl test

### ISSUE THREAD

**Issue by jmsull** [fastpm/fastpm#105]
I was looking at the [fnl test](https://github.com/fastpm/fastpm/blob/6ffdf35d9627499cf91de1e6d9836572e9668b44/tests/standard.lua#L142) that is run by default to get a sense of how to run fastpm with local PNG in the ICs. There are some parameter values in that test but they come with a comment that says "FIXME: what?" - is this the right way to run fastpm with local PNG (i.e. is the comment just outdated)?

@rainwoodman  It seems like you introduced this message in 6e38a2b7604f64db07c4d7420927be46b602eacc (and I'm not sure it was resolved)?

**Comment by rainwoodman** [comment]
Hi,

I believe marcel-sl (mentioned in the commit message) has checked these
fixe mes. I also recall running simulations with the fnl module and
checking the results.

So yes I think the comments are outdated.

Yu

**Comment by jmsull** [comment]
Okay I will close this - thanks
