### ISSUE TITLE
Seed of 0 and 1 return the same initial density field?

### ISSUE THREAD

**Issue by jmsull** [fastpm/fastpm#111]
This may be just seed behavior I don't understand, but when I run a simulation with random_seed = 0 and random_seed = 1, I get back exactly the same initial density field. 

Is this a bug or should I just avoid using seed 0?

**Comment by rainwoodman** [comment]
This is a bit surprising. I don’t know if the underlying rng doesn’t
distinguish between 0 and 1. Perhaps read up the gsl documentation if they
mention anything about similar issues?

Yu

**Comment by jmsull** [comment]
I don't really understand what it means by "original implementation" in the [GSL docs](https://www.gnu.org/software/gsl/doc/html/rng.html?highlight=gsl_rng_set#c.gsl_rng_set), but it does say that only s>=1 will return different streams of random numbers. So s=0 is something that I suppose shouldn't be used. I found a couple of stackexchange posts where people found this issue with 0 and 1 giving the same result as well (no resolution).

**Comment by jmsull** [comment]
I'm going to close this since never using seed 0 and 1 at the same time always works. The only change might be to add a comment somewhere to tell people that this happens?

I will note that this 0/1 thing is a feature of the RANLUX generator used in fastpm - the [user guide](https://luscher.web.cern.ch/luscher/ranlux/guide.pdf) for that code says seeds have to take a value between 1 and 2^31-1, so using 0 must cause a problem somehow.
When I use `gsl_rng_default`, seed 0 and seed 1 return different results. Out of curiosity, is there a particular reason you chose RANLUX?
