### ISSUE TITLE
Potential corrupted Velocity or RSDFactor in output.

### ISSUE THREAD

**Issue by rainwoodman** [fastpm/fastpm#87]
@modichirag recently reported that the VelocityShift computed from RSDFactor * Velocity in certain versions of FastPM looks like is too large by a factor of a H(a) in a z=4 snapshot:

1. RSDFactor * Velocity looks wrong.
2. RSDFactor / (a H(a)) * Velocity looks about right.

**Comment by modichirag** [comment]
I went back and checked that the RSDFactor is correct so we can close the issue without any changes.

**Comment by rainwoodman** [comment]
Thanks for the feedback!
