### ISSUE TITLE
linear_density_redshift does not apply to input LinearDensityK

### ISSUE THREAD

**Issue by ColdThunder** [fastpm/fastpm#89]
I checked the source code in src/fastpm.c.  In the comments it seems that linear_density_redshift should apply to both density field, one is by direct input by LinearDesntiyK, the other by the input power spectrum.  

But in the code I found the immediate return after the reading of the LinearDenstiyK.  No scaling is applied.  It conflicts with the comments around there, saying the input DeltaK/Power spectrum is scaled.

I feel that it's better to scale the density input by LinearDenstiyK option.

**Comment by rainwoodman** [comment]
I think this is fixed in #90 and confirmed by @ColdThunder? Shall we close the issue? @adrianbayer

**Comment by adrianbayer** [comment]
Yes, this has been fixed. Will close now.
