### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by sbird** [fastpm/fastpm#92]
On my linux desktop I cannot run the fastpm tests with the master branch. Makefile.local is Makefile.local.travis. 
I have done:
cd tests
bash runtests.sh
and they fail with the below segfault. Looking at the code, it seems that pm_nc_factor = 0 in the memory allocation code.
It seems that             lua_isnil() 
on line 837 of lua-config.c returns true and the default value of 0 is set. This does not really make sense because the config file does set pm_nc_factor. I suspect some incompatibility with the lua version, which is lua 5.4.3, or the compiler, which is gcc 10.2.0. This is arch linux but I also tried it on a fedora machine where the backtrace was a little different.

[ 0000000.0000 ]: This is FastPM, with libfastpm version 1.0.f1f2510708.
[ 0000000.0022 ]: Configuration {
[ 0000000.0022 ]:       N_eff = 3.045999999999999819,
[ 0000000.0022 ]:       N_nu = 0,
[ 0000000.0022 ]:       Omega_k = 0,
[ 0000000.0022 ]:       Omega_m = 0.30749399999999999,
[ 0000000.0022 ]:       T_cmb = 0,
[ 0000000.0022 ]:       boxsize = 384.0,
[ 0000000.0022 ]:       compute_potential = false,
[ 0000000.0022 ]:       dh_factor = 1.0,
[ 0000000.0022 ]:       enforce_broadband_kmax = 4,
[ 0000000.0022 ]:       every_ncdm = 4,
[ 0000000.0022 ]:       f_nl_type = "none",
[ 0000000.0022 ]:       fof_kdtree_thresh = 8,
[ 0000000.0022 ]:       fof_linkinglength = 0.200000000000000011,
[ 0000000.0022 ]:       fof_nmin = 20,
[ 0000000.0022 ]:       force_mode = "zola",
[ 0000000.0022 ]:       force_softening_type = "none",
[ 0000000.0022 ]:       growth_mode = "ODE",
[ 0000000.0022 ]:       h = 0.677400000000000002,
[ 0000000.0022 ]:       inverted_ic = false,
[ 0000000.0022 ]:       kernel_type = "1_4",
[ 0000000.0022 ]:       kmax_primordial_over_knyquist = 0.25,
[ 0000000.0022 ]:       lc_fov = 0.0,
[ 0000000.0022 ]:       lc_usmesh_alloc_factor = 1.0,
[ 0000000.0022 ]:       lc_usmesh_fof_padding = 10.0,
[ 0000000.0022 ]:       linear_density_redshift = 0,
[ 0000000.0022 ]:       linear_density_redshift_ncdm = 0,
[ 0000000.0022 ]:       lpt_nc_factor = 1,
[ 0000000.0022 ]:       lvk = true,
[ 0000000.0022 ]:       n_shell = 10,
[ 0000000.0022 ]:       n_side = 3,
[ 0000000.0022 ]:       nc = 128,
[ 0000000.0022 ]:       ncdm_freestreaming = true,
[ 0000000.0022 ]:       ncdm_matterlike = true,
[ 0000000.0022 ]:       ncdm_sphere_scheme = "fibonacci",
[ 0000000.0022 ]:       np_alloc_factor = 4.0,
[ 0000000.0022 ]:       painter_support = 2,
[ 0000000.0022 ]:       painter_type = "cic",
[ 0000000.0022 ]:       particle_fraction = 1.0,
[ 0000000.0022 ]:       pgdc = false,
[ 0000000.0022 ]:       pgdc_A = 4.0,
[ 0000000.0022 ]:       pgdc_B = 8.0,
[ 0000000.0022 ]:       pgdc_alpha0 = 0.800000000000000044,
[ 0000000.0022 ]:       pgdc_kl = 2.0,
[ 0000000.0022 ]:       pgdc_ks = 10.0,
[ 0000000.0022 ]:       pm_nc_factor = 3,
[ 0000000.0022 ]:       random_seed = 100,
[ 0000000.0022 ]:       read_powerspectrum = "powerspec.txt",
[ 0000000.0022 ]:       remove_cosmic_variance = false,
[ 0000000.0022 ]:       set_mode_method = "override",
[ 0000000.0022 ]:       shift = false,
[ 0000000.0022 ]:       sigma8 = 0,
[ 0000000.0022 ]:       sort_snapshot = true,
[ 0000000.0022 ]:       w0 = -1,
[ 0000000.0022 ]:       wa = 0,
[ 0000000.0022 ]:       write_lineark = "results-ic/IC",
[ 0000000.0022 ]:       write_nonlineark = "results-ic/fastpm",
[ 0000000.0022 ]:       write_powerspectrum = "results-ic/powerspec",
[ 0000000.0022 ]:       write_snapshot = "results-ic/fastpm",
[ 0000000.0022 ]:       write_whitenoisek = "results-ic/IC",
[ 0000000.0022 ]:       za = false,
[ 0000000.0022 ]:       m_ncdm = { },
[ 0000000.0022 ]:       aout = {
[ 0000000.0022 ]:               0.100000000000000006,
[ 0000000.0022 ]:               0.333333333333333315,
[ 0000000.0022 ]:               0.5,
[ 0000000.0022 ]:               1.0,
[ 0000000.0022 ]:       },
[ 0000000.0022 ]:       lc_glmatrix = {
[ 0000000.0022 ]:               {
[ 0000000.0022 ]:                       1,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:               },
[ 0000000.0022 ]:               {
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       1,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:               },
[ 0000000.0022 ]:               {
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       1,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:               },
[ 0000000.0022 ]:               {
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       1,
[ 0000000.0022 ]:               },
[ 0000000.0022 ]:       },
[ 0000000.0022 ]:       lc_octants = {
[ 0000000.0022 ]:               0,
[ 0000000.0022 ]:               1,
[ 0000000.0022 ]:               2,
[ 0000000.0022 ]:               3,
[ 0000000.0022 ]:               4,
[ 0000000.0022 ]:               5,
[ 0000000.0022 ]:               6,
[ 0000000.0022 ]:               7,
[ 0000000.0022 ]:       },
[ 0000000.0022 ]:       lc_usmesh_tiles = {
[ 0000000.0022 ]:               {
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:                       0,
[ 0000000.0022 ]:               },
[ 0000000.0022 ]:       },
[ 0000000.0022 ]:       output_redshifts = {
[ 0000000.0022 ]:               9.0,
[ 0000000.0022 ]:               2.0,
[ 0000000.0022 ]:               1.0,
[ 0000000.0022 ]:               0.0,
[ 0000000.0022 ]:       },
[ 0000000.0022 ]:       time_step = {
[ 0000000.0022 ]:               0.100000000000000006,
[ 0000000.0022 ]:       },
[ 0000000.0022 ]: }
[ 0000000.0024 ]: np_alloc_factor = 4
[ 0000000.1191 ]: mass of a CDM particle is 230.353 1e10 Msun/h
[ 0000000.1216 ]: BaseProcMesh : 2 x 2
[ 0000000.1216 ]: 1 Threads
[ 0000000.1223 ]: Powerspecectrum file: powerspec.txt
[ 0000000.1242 ]: Found 1769 pairs of values in input spectrum table
[ 0000000.1247 ]: Input power spectrum sigma8 0.815897
[ 0000000.2134 ]: Variance of input white noise is 0.99921342, expectation is 0.99999952
[ 0000000.2134 ]: Writing Fourier white noise to file 'results-ic/IC'.
[ 0000000.2779 ]: Inducing correlation to the white noise.
[ 0000000.3029 ]: Reference linear density is calibrated at redshift 0; multiply by 1 to extract to redshift 0.
[ 0000000.3078 ]: No cdm linear growth rate file input.
[ 0000000.3079 ]: Writing fourier space linear field to results-ic/IC
[ 0000000.3723 ]: writing linear power spectrum to results-ic/powerspec_linear.txt
[ 0000000.3922 ]: Sending ghosts: min = 16512 max = 16512 mean = 16512 std = 0
[ 0000000.3922 ]: Receiving ghosts: min = 16512 max = 16512 mean = 16512 std = 0
[ 0000000.4095 ]: Using sparse Alltoallv
[ 0000000.9734 ]: Using sparse Alltoallv
[ 0000000.9739 ]: Using sparse Alltoallv
[ 0000000.9771 ]: 2LPT ICs set at z=9: E=17.5552 D1=0.127589, D2=0.0161427, f1=0.998774, f2=1.9976
[ 0000001.0027 ]: dx1  : 5.04403 5.44115 6.1141 5.53309
[ 0000001.0027 ]: dx2  : 0.733256 0.719428 0.725769 0.726151
[ 0000001.0347 ]: ==== -> 001 [000 000 000] a_i = 0.1000 a_f = 0.1000 a_r = 0.1000 Action = FORCE(0) ====
[ 0000001.0348 ]: Task 0 Peak memory usage max: 176.336 MB min : 176.148 MB
[ 0000001.0348 ]: S 0x000055e2b847ea50 : 0002166784 :              PMAlloc:             pm2lpt.c:54
[ 0000001.0348 ]: S 0x000055e2b826da40 : 0002166784 :              PMAlloc:             pm2lpt.c:54
[ 0000001.0348 ]: S 0x000055e2b805ca30 : 0002166784 :              PMAlloc:             pm2lpt.c:54
[ 0000001.0348 ]: S 0x000055e2b7e4ba20 : 0002166784 :              PMAlloc:             pm2lpt.c:47
[ 0000001.0348 ]: S 0x000055e2b7c3aa10 : 0002166784 :              PMAlloc:             pm2lpt.c:46
[ 0000001.0348 ]: S 0x000055e2b78acb10 : 0001343488 :          FastPMStore:           pmghosts.c:183
[ 0000001.0348 ]: S 0x000055e2b789bb00 : 0000069632 :            Ghost2Par:           pmghosts.c:180
[ 0000001.0348 ]: S 0x000055e2b768aaf0 : 0002166784 :              PMAlloc:             fastpm.c:674
[ 0000001.0348 ]: S 0x00007f23d8dfc010 : 0119545856 :          FastPMStore:             solver.c:91
[ 0000001.0348 ]: H 0x000055e2b79f4b20 : 0000200704 :              SendBuf:           pmghosts.c:267
[ 0000001.0348 ]: H 0x000055e2b7a61bf0 : 0000200704 :              RecvBuf:           pmghosts.c:266
[ 0000001.0348 ]: H 0x00007f23ecffc010 : 0025169920 :                  DX2:             solver.c:178
[ 0000001.0348 ]: H 0x00007f23ee7fe010 : 0025169920 :                  DX1:             solver.c:174
Killed by Signal 11
Killed by Signal 11
Killed by Signal 11
Killed by Signal 11
PID 515636 - process
TID 515636:
#0  0x00007f886636f87c read
#1  0x0000558608068c01 show_backtrace.isra.0
#2  0x0000558608068de8 OsSigHandler
#3  0x00007f8866370960 __restore_rt
#4  0x0000558608098b90 fastpm_memory_dump_status
#5  0x0000558608098c1e _sys_abort.part.0
#6  0x0000558608098f6c fastpm_memory_alloc_details
#7  0x00005586080b1a9b pm_alloc_details
#8  0x0000558608091a0b fastpm_solver_evolve
#9  0x0000558608058cbb run_fastpm
#10 0x0000558608055550 main
#11 0x00007f88661b5b25 __libc_start_main
#12 0x000055860805569e _start
TID 515639:
#0  0x00007f886628237f __poll
#1  0x00007f8865f71d91
#2  0x00007f8865f67879 event_base_loop
#3  0x00007f886605bd3f
#4  0x00007f8866366299 start_thread
#5  0x00007f886628d053 __clone
TID 515640:
#0  0x00007f886628d39e epoll_wait
#1  0x00007f8865f72996
#2  0x00007f8865f67879 event_base_loop
#3  0x00007f88655dc04f
#4  0x00007f8866366299 start_thread
#5  0x00007f886628d053 __clone
PID 515637 - process
TID 515637:
#0  0x00007f0dc327c87c read
#1  0x0000558b75b08c01 show_backtrace.isra.0
#2  0x0000558b75b08de8 OsSigHandler
#3  0x00007f0dc327d960 __restore_rt
#4  0x0000558b75b38b90 fastpm_memory_dump_status
#5  0x0000558b75b38c1e _sys_abort.part.0
#6  0x0000558b75b38f6c fastpm_memory_alloc_details
#7  0x0000558b75b51a9b pm_alloc_details
#8  0x0000558b75b31a0b fastpm_solver_evolve
#9  0x0000558b75af8cbb run_fastpm
#10 0x0000558b75af5550 main
#11 0x00007f0dc30c2b25 __libc_start_main
#12 0x0000558b75af569e _start
TID 515642:
#0  0x00007f0dc318f37f __poll
#1  0x00007f0dc2e7ed91
#2  0x00007f0dc2e74879 event_base_loop
#3  0x00007f0dc2f68d3f
#4  0x00007f0dc3273299 start_thread
#5  0x00007f0dc319a053 __clone
TID 515644:
#0  0x00007f0dc319a39e epoll_wait
#1  0x00007f0dc2e7f996
#2  0x00007f0dc2e74879 event_base_loop
#3  0x00007f0dc24e904f
#4  0x00007f0dc3273299 start_thread
#5  0x00007f0dc319a053 __clone
PID 515635 - process
TID 515635:
#0  0x00007f23f739487c read
#1  0x000055e2b5359c01 show_backtrace.isra.0
#2  0x000055e2b5359de8 OsSigHandler
#3  0x00007f23f7395960 __restore_rt
#4  0x000055e2b5389d94 fastpm_memory_alloc_details
#5  0x000055e2b53a2a9b pm_alloc_details
#6  0x000055e2b5382a0b fastpm_solver_evolve
#7  0x000055e2b5349cbb run_fastpm
#8  0x000055e2b5346550 main
#9  0x00007f23f71dab25 __libc_start_main
#10 0x000055e2b534669e _start
TID 515645:
#0  0x00007f23f72a737f __poll
#1  0x00007f23f6f96d91
#2  0x00007f23f6f8c879 event_base_loop
#3  0x00007f23f7080d3f
#4  0x00007f23f738b299 start_thread
#5  0x00007f23f72b2053 __clone
TID 515646:
#0  0x00007f23f72b239e epoll_wait
#1  0x00007f23f6f97996
#2  0x00007f23f6f8c879 event_base_loop
#3  0x00007f23f660104f
#4  0x00007f23f738b299 start_thread
#5  0x00007f23f72b2053 __clone
PID 515638 - process
TID 515638:
#0  0x00007f15286a487c read
#1  0x000055c8c6375c01 show_backtrace.isra.0
#2  0x000055c8c6375de8 OsSigHandler
#3  0x00007f15286a5960 __restore_rt
#4  0x000055c8c63a5b90 fastpm_memory_dump_status
#5  0x000055c8c63a5c1e _sys_abort.part.0
#6  0x000055c8c63a5f6c fastpm_memory_alloc_details
#7  0x000055c8c63bea9b pm_alloc_details
#8  0x000055c8c639ea0b fastpm_solver_evolve
#9  0x000055c8c6365cbb run_fastpm
#10 0x000055c8c6362550 main
#11 0x00007f15284eab25 __libc_start_main
#12 0x000055c8c636269e _start
TID 515641:
#0  0x00007f15285b737f __poll
#1  0x00007f15282a6d91
#2  0x00007f152829c879 event_base_loop
#3  0x00007f1528390d3f
#4  0x00007f152869b299 start_thread
#5  0x00007f15285c2053 __clone
TID 515643:
#0  0x00007f15285c239e epoll_wait
#1  0x00007f15282a7996
#2  0x00007f152829c879 event_base_loop
#3  0x00007f152791104f
#4  0x00007f152869b299 start_thread
#5  0x00007f15285c2053 __clone

**Comment by sbird** [comment]
Here is the error on fedora:
[ 0000000.0029 ]: np_alloc_factor = 4
[spb43:156720:0:156720] Caught signal 8 (Floating point exception: integer divide by zero)
[spb43:156721:0:156721] Caught signal 8 (Floating point exception: integer divide by zero)
==== backtrace (tid: 156720) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2a4) [0x7f4c75df7524]
 1  /lib64/libucs.so.0(+0x290cd) [0x7f4c75dfa0cd]
 2  /lib64/libucs.so.0(+0x293aa) [0x7f4c75dfa3aa]
 3  ./../src/fastpm() [0x4ef102]
 4  ./../src/fastpm() [0x4ef026]
 5  ./../src/fastpm() [0x4eef71]
==== backtrace (tid: 156721) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2a4) [0x7f13e549e524]
 1  /lib64/libucs.so.0(+0x290cd) [0x7f13e54a10cd]
 2  /lib64/libucs.so.0(+0x293aa) [0x7f13e54a13aa]
 3  ./../src/fastpm() [0x4ef102]
 4  ./../src/fastpm() [0x4ef026]
 5  ./../src/fastpm() [0x4eef71]
 6  ./../src/fastpm() [0x4a9a98]
 7  ./../src/fastpm() [0x4a9a4b]
 8  ./../src/fastpm() [0x4a403a]
 9  ./../src/fastpm() [0x4a3ef1]
 6  ./../src/fastpm() [0x4a9a98]
 7  ./../src/fastpm() [0x4a9a4b]
 8  ./../src/fastpm() [0x4a403a]
 9  ./../src/fastpm() [0x4a3ef1]
10  ./../src/fastpm() [0x4a32ee]
11  ./../src/fastpm() [0x4a0c0c]
12  ./../src/fastpm() [0x4ee4d7]
10  ./../src/fastpm() [0x4a32ee]
11  ./../src/fastpm() [0x4a0c0c]
12  ./../src/fastpm() [0x4ee4d7]
13  ./../src/fastpm() [0x497f93]
14  ./../src/fastpm() [0x454b07]
15  ./../src/fastpm() [0x453e7c]
16  ./../src/fastpm() [0x43efe8]
17  ./../src/fastpm() [0x408e23]
18  ./../src/fastpm() [0x4064e7]
19  /lib64/libc.so.6(__libc_start_main+0xf2) [0x7f13e76891e2]
20  ./../src/fastpm() [0x40660e]
=================================
13  ./../src/fastpm() [0x497f93]
14  ./../src/fastpm() [0x454b07]
15  ./../src/fastpm() [0x453e7c]
16  ./../src/fastpm() [0x43efe8]
17  ./../src/fastpm() [0x408e23]
18  ./../src/fastpm() [0x4064e7]
19  /lib64/libc.so.6(__libc_start_main+0xf2) [0x7f4c77fe21e2]
20  ./../src/fastpm() [0x40660e]
=================================
Killed by Signal 8
Killed by Signal 8
Thread 4 (Thread 0x7f13e4bb0640 (LWP 156729) "fastpm"):
#0  0x00007f13e7762e9e in epoll_wait () from /lib64/libc.so.6
#1  0x00007f13e5498bfd in ucs_event_set_wait () from /lib64/libucs.so.0
#2  0x00007f13e5493c46 in ucs_async_thread_func () from /lib64/libucs.so.0
#3  0x00007f13e78373f9 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f13e7762b53 in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f13e677d640 (LWP 156725) "fastpm"):
#0  0x00007f13e7762e9e in epoll_wait () from /lib64/libc.so.6
#1  0x00007f13e74638cc in epoll_dispatch.lto_priv () from /lib64/libevent_core-2.1.so.6
#2  0x00007f13e745e235 in event_base_loop () from /lib64/libevent_core-2.1.so.6
#3  0x00007f13e687b786 in progress_engine () from /lib64/libpmix.so.2
#4  0x00007f13e78373f9 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f13e7762b53 in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f13e713d640 (LWP 156723) "fastpm"):
#0  0x00007f13e7757a5f in poll () from /lib64/libc.so.6
#1  0x00007f13e746319d in poll_dispatch.lto_priv () from /lib64/libevent_core-2.1.so.6
#2  0x00007f13e745e235 in event_base_loop () from /lib64/libevent_core-2.1.so.6
#3  0x00007f13e752adb6 in progress_engine () from /usr/lib64/openmpi/lib/libopen-pal.so.40
#4  0x00007f13e78373f9 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f13e7762b53 in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f13e7147bc0 (LWP 156721) "fastpm"):
#0  0x00007f13e78410fc in read () from /lib64/libpthread.so.0
#1  0x0000000000419423 in show_backtrace () at stacktrace.c:75
#2  0x00000000004195d7 in OsSigHandler (no=8) at stacktrace.c:106
#3  <signal handler called>
#4  0x00000000004ef102 in pfft_num_blocks ()
#5  0x00000000004ef026 in pfft_local_block_offset ()
#6  0x00000000004eef71 in pfft_local_block_size_and_offset ()
#7  0x00000000004a9a98 in pfft_decompose_1d ()
#8  0x00000000004a9a4b in pfft_decompose ()
#9  0x00000000004a403a in decompose_nontransposed ()
#10 0x00000000004a3ef1 in local_size_transposed ()
#11 0x00000000004a32ee in pfft_local_size_partrafo_transposed ()
#12 0x00000000004a0c0c in pfft_local_size_partrafo ()
#13 0x00000000004ee4d7 in pfft_local_size_many_dft_r2c ()
#14 0x0000000000497f93 in pfft_local_size_dft_r2c ()
#15 0x0000000000454b07 in pm_init (pm=pm@entry=0x2137870, init=init@entry=0x7ffe0e0d9630, comm=comm@entry=0x8de400 <ompi_mpi_comm_world>) at pmpfft.c:169
#16 0x0000000000453e7c in vpm_create (vpminit=<optimized out>, baseinit=baseinit@entry=0x7ffe0e0d96d0, comm=comm@entry=0x8de400 <ompi_mpi_comm_world>) at vpm.c:44
#17 0x000000000043efe8 in fastpm_solver_init (fastpm=fastpm@entry=0x7ffe0e0da8a0, config=config@entry=0x7ffe0e0dba40, comm=comm@entry=0x8de400 <ompi_mpi_comm_world>) at solver.c:100
#18 0x0000000000408e23 in run_fastpm (config=config@entry=0x7ffe0e0dba40, prr=prr@entry=0x7ffe0e0db970, comm=0x8de400 <ompi_mpi_comm_world>) at fastpm.c:271
#19 0x00000000004064e7 in main (argc=<optimized out>, argv=<optimized out>) at fastpm.c:211
Thread 4 (Thread 0x7f4c75509640 (LWP 156730) "fastpm"):
#0  0x00007f4c780bbe9e in epoll_wait () from /lib64/libc.so.6
#1  0x00007f4c75df1bfd in ucs_event_set_wait () from /lib64/libucs.so.0
#2  0x00007f4c75decc46 in ucs_async_thread_func () from /lib64/libucs.so.0
#3  0x00007f4c781903f9 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f4c780bbb53 in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f4c770d6640 (LWP 156724) "fastpm"):
#0  0x00007f4c780bbe9e in epoll_wait () from /lib64/libc.so.6
#1  0x00007f4c77dbc8cc in epoll_dispatch.lto_priv () from /lib64/libevent_core-2.1.so.6
#2  0x00007f4c77db7235 in event_base_loop () from /lib64/libevent_core-2.1.so.6
#3  0x00007f4c771d4786 in progress_engine () from /lib64/libpmix.so.2
#4  0x00007f4c781903f9 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f4c780bbb53 in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f4c77a96640 (LWP 156722) "fastpm"):
#0  0x00007f4c780b0a5f in poll () from /lib64/libc.so.6
#1  0x00007f4c77dbc19d in poll_dispatch.lto_priv () from /lib64/libevent_core-2.1.so.6
#2  0x00007f4c77db7235 in event_base_loop () from /lib64/libevent_core-2.1.so.6
#3  0x00007f4c77e83db6 in progress_engine () from /usr/lib64/openmpi/lib/libopen-pal.so.40
#4  0x00007f4c781903f9 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f4c780bbb53 in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f4c77aa0bc0 (LWP 156720) "fastpm"):
#0  0x00007f4c7819a0fc in read () from /lib64/libpthread.so.0
#1  0x0000000000419423 in show_backtrace () at stacktrace.c:75
#2  0x00000000004195d7 in OsSigHandler (no=8) at stacktrace.c:106
#3  <signal handler called>
#4  0x00000000004ef102 in pfft_num_blocks ()
#5  0x00000000004ef026 in pfft_local_block_offset ()
#6  0x00000000004eef71 in pfft_local_block_size_and_offset ()
#7  0x00000000004a9a98 in pfft_decompose_1d ()
#8  0x00000000004a9a4b in pfft_decompose ()
#9  0x00000000004a403a in decompose_nontransposed ()
#10 0x00000000004a3ef1 in local_size_transposed ()
#11 0x00000000004a32ee in pfft_local_size_partrafo_transposed ()
#12 0x00000000004a0c0c in pfft_local_size_partrafo ()
#13 0x00000000004ee4d7 in pfft_local_size_many_dft_r2c ()
#14 0x0000000000497f93 in pfft_local_size_dft_r2c ()
#15 0x0000000000454b07 in pm_init (pm=pm@entry=0x165f4b0, init=init@entry=0x7fff1e317cb0, comm=comm@entry=0x8de400 <ompi_mpi_comm_world>) at pmpfft.c:169
#16 0x0000000000453e7c in vpm_create (vpminit=<optimized out>, baseinit=baseinit@entry=0x7fff1e317d50, comm=comm@entry=0x8de400 <ompi_mpi_comm_world>) at vpm.c:44
#17 0x000000000043efe8 in fastpm_solver_init (fastpm=fastpm@entry=0x7fff1e318f20, config=config@entry=0x7fff1e31a0c0, comm=comm@entry=0x8de400 <ompi_mpi_comm_world>) at solver.c:100
#18 0x0000000000408e23 in run_fastpm (config=config@entry=0x7fff1e31a0c0, prr=prr@entry=0x7fff1e319ff0, comm=0x8de400 <ompi_mpi_comm_world>) at fastpm.c:271
#19 0x00000000004064e7 in main (argc=<optimized out>, argv=<optimized out>) at fastpm.c:211
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

**Comment by rainwoodman** [comment]
Found a potential fix. Fixed mine on gcc-10.

**Comment by sbird** [comment]
That fixes it for me, thanks!
