### ISSUE TITLE
lightcone construction 

### ISSUE THREAD

**Issue by czymh** [fastpm/fastpm#97]
Hello, I am trying to run a lightcone (z~2.0) simulation with fastpm. 
The simulation setup is as followed:
```
nc = 128
T = 40
B= 2
boxsize = 500
time_step = loglinspace(0.1, 0.2, 1.0, 10, T)
fov = 10
lc_amin = 0.332
lc_amax = 1.0
lc_usmesh_tiles = fastpm.outerproduct({0}, {0}, {0,1,2,3, 4,5,6,7})
```
The error appeared:
```
7966 [ 0000017.8011 ]: usmesh: intersection step 7 / 12 a = 0.331027 0.330818 . \\
7967 [ 0000017.8011 ]: usmesh: number of bounding box intersects shell r = (3372.78 3393.76), min = 1 max = 1, mea     n=1
7968 [ 0000017.8011 ]: usmesh: intersection step 8 / 12 a = 0.330818 0.330609 .
7969 [ 0000017.8011 ]: usmesh: number of bounding box intersects shell r = (3372.78 3393.76), min = 1 max = 1, mea     n=1
7970 [ 0000017.8011 ]: usmesh: intersection step 9 / 12 a = 0.330609 0.330399 .
7971 [ 0000017.8011 ]: usmesh: number of bounding box intersects shell r = (3372.78 3393.76), min = 1 max = 1, mea     n=1
7972 [ 0000017.8011 ]: usmesh: intersection step 10 / 12 a = 0.330399 0.33019 .
7973 [ 0000017.8012 ]: usmesh: number of bounding box intersects shell r = (3372.78 3393.76), min = 1 max = 1, mea     n=1
7974 [ 0000017.8012 ]: usmesh: intersection step 11 / 12 a = 0.33019 0.335 .
7975 ThisTask = 0 [ 0000017.8012 ]: drift beyond factor's available range.
7976 ThisTask = 1 [ 0000017.8011 ]: drift beyond factor's available range.
7977 ThisTask = 2 [ 0000017.8011 ]: drift beyond factor's available range.
7978 ThisTask = 3 [ 0000017.8011 ]: drift beyond factor's available range.
7979 ThisTask = 4 [ 0000017.8013 ]: drift beyond factor's available range.
7980 ThisTask = 5 [ 0000017.8011 ]: drift beyond factor's available range.
7981 ThisTask = 6 [ 0000017.8013 ]: drift beyond factor's available range.
7982 ThisTask = 7 [ 0000017.8011 ]: drift beyond factor's available range.
```

If I change the set `lc_usmesh_tiles = fastpm.outerproduct({0}, {0}, {0,1,2,3, 4,5,6,7})` to `lc_usmesh_tiles = fastpm.outerproduct({0}, {0}, {0})`.
This error disappeared.
Also, I found that using a very large timestep (>hundreds) can also solve this problem.
So I want to know whether there is a specific relation among these parameters or recommended setup when we run a lightcone with z > 1.0.
Thank you!

**Comment by rainwoodman** [comment]
I am able to reproduce the bug locally; I'm taking a quick a look, and my gut feeling is a fix is not hard. I suspect it is a numerical issue during the iterative solver for the horizon intersection.  The reason the error disappears with your single tile set up is because the tile doesn't overlap with a=0.33 any more.

The Crow Canyon simulations went to up to z=2.2, where I used 40 steps; but that simulation was a different geometry, full sky a few Gpc/h box with 8 (or 16) tiles.

**Comment by rainwoodman** [comment]
I found a bug, and after fixing it I was able to run your configuration (with nc=16) on a single rank to z=0, writing out a lightcone like this:
![Figure_1](https://user-images.githubusercontent.com/138060/132268155-b6c030e6-bbe9-47a2-b739-bf1ab0cd9f92.png)

Let me know if the problem persists (by reopening). Thanks!
